import HeaderExtractorOptions from './header.model';

export default {
  maxHeaderLines: 8,
  minLineLength: 2,
  headerDelimiters: [
    { pattern: /[\d\w]/, negative: true },
    /^\s*Artikelname\s*$/i,
    /^\s*Preis:?\s*$/i,
    /^UID\sNr/i,
    /^\s*EUR\s*$/i,
    /^\s*\d+[,.]\d\d\s*$/i,
    /^\s*St\.?Nr\.?/i,
    /[oö]ffnungszeit(en)?/i,
    /(^|\s)Kartenzahlu[np]g($|\s)/i,
    /(^|\s)Bezahlung($|\s)/i,
    /^€/i,
    /^\d+\sCashier$/i,
    { pattern: /(Quittung|Rechnung)/i, minLine: 5 },
    /mo-(fr|sa|so):? ?([01]\d|2[0-4])( ?:? ?[0-5]\d)? ?(-|bis) ?([01]\d|2[0-4])( ?:? ?[0-5]\d)? ?(uhr)?/i,
  ],
  irrelevantPatterns: [
    /(^| )[*XжN ]*(Karten|K[uv]nden|H(ä|ae?)ndler)bele[gqa][*XжN]*( |$)/gim,
    /(^| ) ?-? ?K ?-? ?[a-z0-9\- ]+B ?-? ?E ?-? ?L ?-? ?E ?-? ?[Gqa] ?-? ?/gim, // Kundenbeleg with " ?-? ?" between letter matchers
    /Bedient von: [a-z]+/i,
    /www?\s?\.\s?[a-z\-]+\s?\.\s?[a-z]+(\/[a-z\-_\d%]+)*\/?/i,
    /Vielen Dank\s?(,[a-z\s&äüö]+[\?!.])?/gim,
    /Bis bald!?/i,
    /Obj(\.|ekt)-?Nr\.?:?\s?\d+(\s|$)/i,
    /K[SA]\.\s?\d+/i,
    /(Term(inal)?[\- ]?ID|TA[- ]Nr\.?) ?:?( ?\d+)?/gim,
    /(^| )ID ?:? ?\d+/gim,
    /^:\s*/,
    /Bed\.?Nr\.?:?\s?\d+/i,
    /Kasse\s?\d+/i,
    /BNr\.?\s?\d+/i,
    /wir haben f(ü|ue?)r sie ge(ö|oe?)ffnet[:!\.]?/i,
    /t(ä|ae?)glich ab \d+( uhr)?/i,
    /rgnr\.?:?\s?\w+/i,
    /Zahlungsart/i,
    /Kellner:?\s?\d+/i,
    /Tisch:?\s?\d+/i,
    /(^| )Arbeitszettel( |$)/gim,
    /(sagt )?danke f(ü|ue?)r Ihren Einkauf/i,
    /(und )?auf Wiedersehen/i,
    /Bon[\- ]?ID:?\s?(\d+)?/im,
    /wir danken\sf(ü|ue?)r ihren einkauf[!.]?/gim,
    /[HW](ä|ae?)hrung:? ?(EURO?)?/gim,
    /(^| )Rechnung( |$)/gim,
    / ?-? ?Q ?-? ?U ?-? ?I ?-? ?T ?-? ?T ?-? ?U ?-? ?N ?-? ?G ?-? ?/gim,
    /Bedienung:? ?/,
    /(Steuer|USt)[ \-]?(ID)?(Nr)?\.?:? ?(DE ?)?[\d\/]+/i,
    /^Lieferzeit$/gim,
    /Tankstellen-?Nr\.?:? ?\d+/gi,
    /^\d{1,4}$/gm,
    /(^| )(Beleg|Trace)(\s*\-?\s*Nr\.?|nummer):? ?(\d+)?/gim,
    /(^| )Datum([ :]|$)/gim,
    /(^| )[UJ]hrzeit:?([ a-z\d():;]*Uhr)?( |$)/gim,
    /^Uhr$/gim,

    /(^| )Zwischensumme( |$)/gim,
    /(?<=\n)\d+ ?total ?\d*( |$)/gim,

    /(^| )Fax[.:]?( ?[\dog\-\/ ]+)?( |$)/gim,
    /(^| )\(?\s?[O0]rtstarif\s?\)?( |$)/gim,

    /^[a-z][^a-z\d]$/gim, // indicate wrongly detected text
  ],
  trimPatterns: [
    /^[ *жxN]+$/i,
    /^[ *xжN]*[ *ж]/i,
    /[ *ж][ *жxN]*$/i,
    /^[,\/]/,
    /[,\/]$/,
  ],
  fixes: [
    {
      pattern: /(^|\s)(?:6mbH|GabH|Gmbh)(\s|$)/g,
      replaceWith: '$1GmbH$2',
    },
    {
      pattern: /^(.*[a-z].*)GMBH(\s|$)/g,
      replaceWith: '$1GmbH$2',
    },
  ],
} as HeaderExtractorOptions;
