dist: trusty
language: node_js
node_js:
  - '10'
  - '11'
cache:
  npm: true
env:
  matrix:
    - TZ=UTC
    - TZ=CET
install:
  - npm install
script:
  - npm run test -- --silent
  - npm run build
jobs:
  include:
    - stage: sonar
      env: TZ=UTC
      node_js:
        - '11'
      addons:
        sonarcloud:
          organization: dexpenses
          token:
            secure: QAxtfXu83C9L4SNuNNlNKhFuqxVs1VGeJyUWDytgHyMfo2297HVTBEl0QYOTwtJg3x8XkOptXx71fzB+wKiY/uhhhT+hafSYgZKDz4lMMywuAlV5YEioMrsRv+4EEh5o3ucnCtWPTm3zV3wttxvx2ZunK/q94w6WH0R4Otuh9HCS4ZMWFy8EhiRD9tsKuLDuNhERlIejUbSvtA7MS32pzE4hqEWBM1vEu8whZ4zDEh2EawVvtwmJ/gDFz/GGfkcEKmLzu8lzAy4zjj5U9MRKsYgd0GjiIJLGVAs3DLEw0Y4+U+rss0/nD4Ar1zLDX+Q3T02tXTj+r3jzhGQMZ39AkfDGQLC3Y60gUUNWbGInvsGkOqXhLOZjJ1AJG4Xev77fowydPmACM6uzfJQyCvIwkIbZuPc9WN45Be/qIpik84W9p3Fvq6GrOSOilk4GwceVJ0MMJhlNnE0z4Vey/xPh/PWNUe0nWUpH4cNJJeX511LFSIamtx0sL8TuMUi17BzzEmmL3pyhTFb3XOfM7Cfv3nZwbuTmkKeM1KUH5aTfeDAit2hiFNrjQdJz6JyFsvgW5Xl6DoKG+ypFOgzStHcmDAPn8S+R9RBrfnovuYqjSJ8e1U+/GC7rk6+ut9OeL5x252F6FYtRCcxo427x1mnUrOVWSzouoSB/m3Ka7OZ7HmA=
      script:
        - npm run test:coverage
        - npm run lint:sonar
        - sonar-scanner
